version: '3.8'


services:
 postgres:
    image: postgres:latest
    
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password1
      POSTGRES_USER: postgres
      POSTGRES_DB: some-db
 



 redis_cache:
  image: redis  #from hub.docker.com it will come
  ports:
    - "6379:6379"
  

  

  
