version: '3.8'

services:
  react-app-test:
    image: react-docker
    stdin_open: true
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - "./:/app"
      - "/app/node_modules/"
